version: "3"
services:
  web:
    image: nginxinc/nginx-unprivileged
    ports:
      - "90:80"
      - "9090:8080"
      - "9001:8001"
      - "9002:8002"
      - "9003:8003"
    volumes: 
      - ./data:/home/nginx
      - ./conf:/etc/nginx/conf.d
      - ${PWD}/global-config/nginx.conf:/etc/nginx/nginx.conf
      - ./logs:/home/logs